modLoader = "javafml"
loaderVersion = "[36,)"
issueTrackerURL = "https://github.com/Redfire75369/Balanced-Clay-Tools/issues"
license = "MPL-2.0"
showAsResourcePack = false

[[mods]]
modId = "balancedclaytools"
version = "${file.jarVersion}"
displayName = "Balanced Clay Tools"
updateJSONURL = ""
displayURL = "https://github.com/Redfire75369/Balanced-Clay-Tools"
authors = "Redfire"
logoFile = ""
description = '''Balanced Clay Tools'''

[[dependencies.balancedclaytools]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.balancedclaytools]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"
